language: ruby
rvm:
  - 2.3.8
  - 2.4.6
  - 2.5.5
  - 2.6.3

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle exec rubocop lib spec -R --format simple
  - bundle exec rspec
  - bundle exec codeclimate-test-reporter
